import "@/styles/_global.scss";
import SmoothScroll from "@/components/animations/SmoothScroll";

export const metadata = {
  title: "CVR Glass Bird Hotel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
